### ISSUE TITLE
Can not parse this page

### ISSUE THREAD

**Issue by matiasmax** [hujinglin/MVA-Downloader#3]
For example I introduce this URL:

https://mva.microsoft.com/en-us/training-courses/introducci-n-a-json-con-c--12742?l=xxtX274UB_8805494542

I tried with this one:
https://mva.microsoft.com/en-us/training-courses/introducci-n-a-json-con-c--12742

For both cases I get this error: Can not parse this page.

**Comment by tuhintarafder6** [comment]
Same for me too when using this link - 
https://mva.microsoft.com/en-US/training-courses/c-fundamentals-for-absolute-beginners-16169
Did you find any fix?

**Comment by hujinglin** [comment]
Bug fixed. It is caused by missing some request headers when I crawling the MVA page:)

**Comment by matiasmax** [comment]
@hujinglin excellent!

**Comment by tuhintarafder6** [comment]
@hujinglin thanks :)

**Comment by prrandrade** [comment]
Sorry, but the problem reappeared... :S

**Comment by hujinglin** [comment]
@prrandrade  Sorry, I have fixed it,  run _npm install_ again please
I use phantomjs to crawl the MVA page now~

**Comment by prrandrade** [comment]
Sorry to say that... but it looks like the problem remains :(

I tried with this link: https://mva.microsoft.com/en-us/training-courses/xamarin-for-absolute-beginners-16182

And, after thinking for several seconds, the MVA Downloader page returns with 'can not parse this page'

**Comment by hujinglin** [comment]
@prrandrade Have you pulled the newest code and and installed the node_modules ? I tried your link is fine~

**Comment by prrandrade** [comment]
Yeah, you're right... my work Internet is more restricted than I thought... Thanks!

But there are some minor errors with subtitles... for example <br/> are ignored because of .text(). I have no nodejs experience, but that primary change is working here:

$('p').each(function (index) {      	
        var $item = $(this)
        var itemHtml = $item.html().replace('<br/>', '\r\n')
        var itemText = $("<div />").html(itemHtml).text()        
        var begin = $item.attr('begin')
        var end = $item.attr('end')
        srt += index + 1 + '\r\n' + begin + ' --> ' + end + '\r\n' + itemText + '\r\n\r\n'
      })

**Comment by hujinglin** [comment]
@prrandrade Thanks a lot!  I have fixed the subtitle bug :)

**Comment by naivefeng** [comment]
I think we can fetch all courses link from [sitemap](https://mva.microsoft.com/sitemap_index.xml).

**Comment by DaviBittencourt** [comment]
I'm new here, can anyone explain to me how to run this project on my machine, what do I have to do to make it work? Only run in the browser? Here is a message "Can not parse this page"

**Comment by hujinglin** [comment]
@naivefeng  no space to save 😄

**Comment by hujinglin** [comment]
@DaviBittencourt tell me the link you are trying to parse, please

**Comment by DaviBittencourt** [comment]
I tried with these:

https://mva.microsoft.com/en-US/training-courses/introduction-to-aspnet-core-10-16841?l=JWZaodE6C_5706218965

https://mva.microsoft.com/en-US/training-courses/intermediate-aspnet-core-10-16964?l=Kvl35KmJD_4306218965#

https://mva.microsoft.com/en-US/training-courses/aspnet-core-10-crossplatform-17039?l=xVagIgJOD_7201937555#

**Comment by DaviBittencourt** [comment]
@hujinglin Are using another tool to download the courses of the MVA Or is there only this is?
